<script setup>
import Icon from '@/components/icon/LucideIcon.vue';
import { ref } from 'vue';
const props = defineProps([
    'classValue', 
    'buttonText', 
    'icon', 
    'hover_icon', 
    'hover_animation',   
    'icon_position',
    'width',
    'pre_loader',
    'disabled',
    

]) 
const hover_icon_status = ref(false)
// if hover_animation is true then add hover effect
//  
// :style="{ 'width':  width ? width : 'auto' }" 



</script>

<template> 
    <button   @mouseover="hover_icon_status = true"  @mouseleave="hover_icon_status = false"
        :style="{ 'width':  width ? width : 'auto' }" 
        :class="[
            classValue,
            { 'disabled': props.pre_loader || props.disabled },
            { 'tfhb-icon-hover-animation': props.hover_animation }
        ]" 
    >
        <span   class="tfhb-button-icon" :class="icon_position" v-if="icon_position == 'left' && icon">
             
            <Icon v-if="hover_icon && props.pre_loader != true" class="tfhb-btn-hover-icon" :name="hover_icon"  size=20 /> 
            <svg v-if="props.pre_loader == true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: block; background: transparent;" width="20" height="20" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-dasharray="164.93361431346415 56.97787143782138" r="35" stroke-width="9" stroke="#ffffff" fill="none" cy="50" cx="50">
                <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="1s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
            </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg> 
            <Icon v-else class="tfhb-btn-icon"  :name="icon"  size=20 /> 
        </span>
        <span class="tfhb-button-text">{{ buttonText }} </span>
         
         <!-- {{ hover_icon_status }} -->
         <span  class="tfhb-button-icon" :class="icon_position" v-if="icon_position != 'left' && icon" >

            <Icon v-if="hover_icon && props.pre_loader != true" class="tfhb-btn-hover-icon" :name="hover_icon"  size=20 /> 
            <svg v-if="props.pre_loader == true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: block; background: transparent;" width="20" height="20" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-dasharray="164.93361431346415 56.97787143782138" r="35" stroke-width="9" stroke="#ffffff" fill="none" cy="50" cx="50">
                <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="1s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
            </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg> 
            <Icon v-else class="tfhb-btn-icon"  :name="icon"  size=20 /> 
        </span>
           
         
         
    </button>
</template>

<style scoped>

</style> 