(function ($) {
	  
    $(document).ready(function () { 
		let tfhb_local_timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
		const tfhb_i18n = tfhb_app_booking.i18n;

		// Check if
		if( 'Asia/Calcutta' == tfhb_local_timeZone ){
			tfhb_local_timeZone = 'Asia/Kolkata'; // convert to Indian Standard Time (IST)
		}

		// function tfhb translate 
		function tfhbTranslate(key) {
            return tfhb_i18n[key] || key ;
        }
		function tfhbTranslateNumber(key) { 
			// provided key like 2025 breack down and replace each letter with translation
			return key.toString().split('').map(function (letter) { 
                return tfhbTranslate(letter);
            }).join('');
        }
		function tfhbTranslateTimeSlot(key) {  
			// key like "09:00 AM " AM string   
			if(key.slice(6, 8) != ''){
				return tfhbTranslateNumber(key.slice(0, 2)) + ':' + tfhbTranslateNumber(key.slice(3, 5)) +' ' + tfhbTranslate(key.slice(6, 8));

			}else{
				return tfhbTranslateNumber(key.slice(0, 2)) + ':' + tfhbTranslateNumber(key.slice(3, 5));
			}
        }

		function tfhbPad(value) {
			return value.toString().padStart(2, '0');
		}

		function tfhbDateFormatFromSettings(defaultFormat) {
			if (typeof tfhb_app_booking === 'undefined' || !tfhb_app_booking.general_settings) {
				return defaultFormat;
			}

			var format = tfhb_app_booking.general_settings.date_format;
			if (typeof format !== 'string' || format.trim() === '') {
				return defaultFormat;
			}

			if (format.trim().toLowerCase() === 'default') {
				return defaultFormat;
			}

			return format.trim();
		}

		function tfhbFormatDateByPattern(dateObj, pattern) {
			if (!dateObj || isNaN(dateObj.getTime())) {
				return '';
			}

			var monthLong = [
				'January', 'February', 'March', 'April', 'May', 'June',
				'July', 'August', 'September', 'October', 'November', 'December'
			];
			var monthShort = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
			var weekLong = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
			var weekShort = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

			var map = {
				d: tfhbTranslateNumber(tfhbPad(dateObj.getDate())),
				j: tfhbTranslateNumber(dateObj.getDate()),
				m: tfhbTranslateNumber(tfhbPad(dateObj.getMonth() + 1)),
				n: tfhbTranslateNumber(dateObj.getMonth() + 1),
				Y: tfhbTranslateNumber(dateObj.getFullYear()),
				y: tfhbTranslateNumber(dateObj.getFullYear().toString().slice(-2)),
				F: tfhbTranslate(monthLong[dateObj.getMonth()]),
				M: tfhbTranslate(monthShort[dateObj.getMonth()]),
				l: tfhbTranslate(weekLong[dateObj.getDay()]),
				D: tfhbTranslate(weekShort[dateObj.getDay()])
			};

			var output = '';
			for (var i = 0; i < pattern.length; i++) {
				var ch = pattern[i];
				if (ch === '\\') {
					i += 1;
					output += pattern[i] || '';
					continue;
				}
				output += Object.prototype.hasOwnProperty.call(map, ch) ? map[ch] : ch;
			}

			return output;
		}

        // Initialize the Date Picker
        /**
         * Time Zone Change
         * @author Jahid
         */
        $(document).on('click', '.tfhb-timezone-tabs ul li', function (e) {
            $('.tfhb-timezone-tabs ul li').removeClass('active');
            var $this = $(this);
            $this.addClass('active');
        });

        // });
	
		/**
		 * Time Select
		 * @author Sydur
		 * */ 
		$('.tfhb-meeting-box').each(function(){

			// Get Calender Id
			let $this = $(this),
			 	calenderId = $this.attr('data-calendar'),
				calenderData =  eval("tfhb_app_booking_" + calenderId), 
				preloader =  `<div class="tfhb-preloader"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: block; background: transparent;" width="200" height="200" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-linecap="round" fill="none" stroke-dasharray="51.83627878423159 51.83627878423159" stroke="#2e6b38" stroke-width="4" r="33" cy="50" cx="50">
				<animateTransform values="0 50 50;360 50 50" keyTimes="0;1" dur="1s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
			  </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg></span></div>`;
			  
 

			let date = new Date();
			let year = date.getFullYear();
			let month = date.getMonth();
		 
			const tfhb_calendar_navs = $this.find(".tfhb-calendar-navigation span")  
			// Array of month names
			const months = [
				"January",
				"February",
				"March",
				"April",
				"May",
				"June",
				"July",
				"August",
				"September",
				"October",
				"November",
				"December"
			]; 


			tfhb_date_manipulate( $this, calenderData, year, month, date, months);


			// Attach a click event listener to each icon
			tfhb_calendar_navs.each(function() {
				// When an icon is clicked
				$(this).on("click", function() { 
					// or "tfhb-calendar-next"
					month = $(this).attr("id") === "tfhb-calendar-prev" ? month - 1 : month + 1;
		
					// Check if the month is out of range
					if (month < 0 || month > 11) {
		
						// Set the date to the first day of the 
						// month with the new year
						date = new Date(year, month, new Date().getDate());
		
						// Set the year to the new year
						year = date.getFullYear();
		
						// Set the month to the new month
						month = date.getMonth();
					} else {
		
						// Set the date to the current date
						date = new Date();
					}
		
					// Hide the time slot with animation
					$this.find('.tfhb-meeting-times').animate({left: "-50%", width: 0, opacity: 0 }, 300,
					function() {
						$(this).css("display", "none");

					});

					
					// Call the tfhb_date_manipulate function to 
					// update the tfhb-calendar display
					tfhb_date_manipulate( $this, calenderData, year, month, date, months);
				
					// first date of the month exp: 
					// 2021-04-01
					var current_date = new Date(year, month, 2).toISOString().split('T')[0];  
					setTimeout(function(){
						// Your code here 
						tfhb_times_manipulate( $this, current_date, calenderData);  
					}, 1000); // 2000 milliseconds = 2 seconds
 


				});
			});

			// Select Date 
            $($this).on('click', '.tfhb-calendar-dates li', function (e) {  
				var $this_li = $(this);
				if($this_li.hasClass('inactive')){
					return false;
				} 
				
				// tfhb-meeting-times  with animation 
				// $this.find('.tfhb-meeting-times').show();
				$this.find('.tfhb-meeting-times').css("display", "block").animate({left: "0%", opacity: 1, width: 224}, 400,);


				$this.find('.tfhb-available-times').removeClass('inactive');
				$this.find('.tfhb-available-times').html('');
				$this.find('.tfhb-available-times').append('<ul></ul>');

				var selected_date = $this_li.attr('data-date'); 
				$this.find("#meeting_dates").val(selected_date);

				// Safely create a Date object (adding 'T00:00:00' ensures local time)
				var dateObj = new Date(selected_date + 'T00:00:00');

				// Fallback for invalid date
				if (isNaN(dateObj.getTime())) {
					console.error('Invalid date:', selected_date);
					return;
				}

				var selected_date_format = tfhbFormatDateByPattern(
					dateObj,
					tfhbDateFormatFromSettings('l, F j')
				);

				// Set the formatted date in the element
				$this.find('.tfhb-meeting-times .tfhb-select-date').html(selected_date_format);
				// get selected date calenderData.calander_available_time_slot
				var selected_date_time_slot = calenderData.calander_available_time_slot[selected_date]; 
				// if selected_date_time_slot is not empty
				// then append the time slot
				// else show the message
				if(selected_date_time_slot.length > 0){
					for (var i = 0; i < selected_date_time_slot.length; i++) { 
						var remaining = '';
						// if selected_date_time_slot[i].remaining is not undefined then show the time slot
 						if(selected_date_time_slot[i].remaining != undefined){
							 remaining = '<span class="tfhb-time-slot-remaining tfhb-flexbox"><span></span>'+tfhbTranslateNumber(selected_date_time_slot[i].remaining)+' '+tfhbTranslate('seats left') +'</span>';
						}
						// Remove 
						// Add with animation when data available
						$this.find('.tfhb-available-times ul').append('<li class="tfhb-flexbox"> <div class="time" data-time-start="'+ selected_date_time_slot[i].start +'" data-time-end="'+ selected_date_time_slot[i].end +'">' + tfhbTranslateTimeSlot(selected_date_time_slot[i].start) + remaining + ' </div> </li>');

					}
				}else{
					$this.find('.tfhb-available-times ul').append('<li class="tfhb-flexbox"> <div>No time slot available in this date ! Try another date.</span> </div>');
				}

				$this.find('.tfhb-calendar-dates li').removeClass('active');  
				$this_li.addClass('active');
				 
 
			});
 
            $this.find('#attendee_time_zone_' + calenderId+'').on('change', function (e) {  
			 
				// Hide the time slot with animation 
				$this.find('.tfhb-meeting-times').animate({left: "-50%", width: 0, opacity: 0 }, 300,
				function() { 
					$(this).css("display", "none");

					
				});

				var current_date = new Date(year, month, 2).toISOString().split('T')[0];  
			 
				// Get the first day of the month 
				tfhb_times_manipulate( $this, current_date, calenderData);    
				
			});
            $this.find('input[name="tfhb_time_format"]').on('change', function (e) { 
				
				var current_date = new Date(year, month, 2).toISOString().split('T')[0];  
			  
				tfhb_times_manipulate($this, current_date, calenderData, function() { 
					$this.find('.tfhb-calendar-dates li.active').trigger('click');    
					// Your logic here
				});
				
			});

			// Get the Select2 dropdown element
			const $timezoneSelect = $this.find('#attendee_time_zone_' + calenderId);

			// Check if the element exists
			if ($timezoneSelect.length) {
				// Initialize Select2 with options
				$timezoneSelect.select2({
					dropdownCssClass: 'tfhb-select2-dropdown',
				});
		
				// Set the value and trigger the change event
				$timezoneSelect.val(tfhb_local_timeZone).trigger('change'); 
			}

			/**
			* Time Select
			* @author Jahid
			*/
			// $this.find('input[name="tfhb_time_format"], .tfhb-time-zone-select').on('change', function (e) { 
            // $this.find('.tfhb-available-times li .time').on('click', function (e) {
			$($this).on('click', '.tfhb-available-times li .time', function (e) { 
				$this_time = $(this);
				$('.tfhb-available-times li .time').removeClass('active');

				// Your code here 
				$('.tfhb-available-times li .next').remove(); 
				var selected_time_start = $this_time.attr('data-time-start');  
				var selected_time_end = $this_time.attr('data-time-end');
				$this.find("input[name='meeting_time_start']").val(selected_time_start);
				$this.find("input[name='meeting_time_end']").val(selected_time_end);
			
				$this_time.parent().append('<span class="next tfhb-flexbox tfhb-gap-8"> '+tfhbTranslate('Next')+'<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1 10L14 10" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M9 4.16666L14.8333 9.99999L9 15.8333" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>');
				$this_time.addClass('active');
				

			});
 
 			$($this).on('click', '.tfhb-available-times li .next', function (e) {  
				
				var time_zone = $this.find('#attendee_time_zone_'+calenderId).val();
				var meeting_dates = $this.find("#meeting_dates").val();
				var meeting_time_start = $this.find("#meeting_time_start").val();
				var meeting_time_end = $this.find("#meeting_time_end").val(); 

				var thimeZone_html = `<li class="tfhb-flexbox tfhb_time_zone_info tfhb-gap-8">
						<input type="hidden" id="recurring_maximum" name="recurring_maximum" value="' . esc_attr( $meeting['recurring_maximum'] ) . '">
						<div class="tfhb-icon">  
							<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
								<g clip-path="url(#clip0_1840_26071)">
									<path d="M8.00065 14.6667C11.6825 14.6667 14.6673 11.6819 14.6673 8.00001C14.6673 4.31811 11.6825 1.33334 8.00065 1.33334C4.31875 1.33334 1.33398 4.31811 1.33398 8.00001C1.33398 11.6819 4.31875 14.6667 8.00065 14.6667Z" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
									<path d="M8.00065 1.33334C6.28881 3.13078 5.33398 5.51784 5.33398 8.00001C5.33398 10.4822 6.28881 12.8692 8.00065 14.6667C9.71249 12.8692 10.6673 10.4822 10.6673 8.00001C10.6673 5.51784 9.71249 3.13078 8.00065 1.33334Z" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
									<path d="M1.33398 8H14.6673" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
									</g>
									<defs>
									<clipPath id="clip0_1840_26071">
									<rect width="16" height="16" fill="white"/>
									</clipPath>
									</defs>
							</svg>
						</div> 
						<div>
							`+time_zone+`(`+tfhbTranslateTimeSlot(meeting_time_start)+`)
						</div>
					</li>`;
					// date time format like that  9:00pm, Saturday, April 25
					
				var date_time = new Date(meeting_dates + 'T00:00:00');
				var selected_date_format = tfhbFormatDateByPattern(
					date_time,
					tfhbDateFormatFromSettings('l, F j, Y')
				);
				var date_time_html = `<li class="tfhb-flexbox tfhb_date_time_info tfhb-gap-8">
						<input type="hidden" id="recurring_maximum" name="recurring_maximum" value="' . esc_attr( $meeting['recurring_maximum'] ) . '">
						<div class="tfhb-icon">  
							<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M5.33398 1.33334V4.00001" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M10.666 1.33334V4.00001" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M12.6667 2.66666H3.33333C2.59695 2.66666 2 3.26361 2 3.99999V13.3333C2 14.0697 2.59695 14.6667 3.33333 14.6667H12.6667C13.403 14.6667 14 14.0697 14 13.3333V3.99999C14 3.26361 13.403 2.66666 12.6667 2.66666Z" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M2 6.66666H14" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
								<path d="M6 10.6667L7.33333 12L10 9.33334" stroke="#273F2B" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
							</svg>
						</div> 
						<div>
							`
							+selected_date_format+
							`
						</div>
					</li>`;

					$this.find('.tfhb-meeting-details ul').append(thimeZone_html);
					$this.find('.tfhb-meeting-details ul').append(date_time_html);

				// Your code here 
				$this.find('.tfhb-timezone').hide();
				

				$this.find('.tfhb-meeting-times').animate({left: "-50%", width: 0, opacity: 0 }, 300,
				function() {
					$(this).css("display", "none");

					
				});
				$this.find('.tfhb-calander-times').animate({
					left: "-5%", 
					opacity: 0, 
				}, 400, function() {
					// After animation is complete, hide the element
					$(this).css("display", "none");

					$this.find('.tfhb-meeting-booking-form').css("display", "block").animate({left: "0", opacity: 1, width: 536 }, 300);
				});
 

				
			});

			// Full Description Showing
			$this.on('click', 'span.tfhb-see-description', function() {
				$this.find('.tfhb-short-description').slideUp();
				$this.find('.tfhb-full-description').slideDown();
			});
	
			// See Less Description Showing
			$this.on('click', 'span.tfhb-see-less-description', function() {
				$this.find('.tfhb-full-description').slideUp();
				$this.find('.tfhb-short-description').slideDown();
			});

			$($this).on('click', '.tfhb-meeting-booking-form .tfhb-back-btn', function (e) { 
 
				$this.find('.tfhb-meeting-booking-form').animate({
					left: "-5%", 
					opacity: 0
				}, 300, function() {
					// After animation is complete, hide the element
					$(this).css("display", "none"); 

					$this.find('.tfhb-timezone').show();

					$this.find('.tfhb-calander-times').css("display", "flex").animate({
						left: "0", 
						opacity: 1
					}, 200, function() { 
						// After animation is complete, hide the element 
					});


					$this.find('.tfhb-meeting-times').css("display", "block").animate({left: "0", width: 224}, 400, 
					function() {
						$(this).css("opacity", "1");

						$this.find('.tfhb-meeting-details ul .tfhb_time_zone_info').remove();
						$this.find('.tfhb-meeting-details ul .tfhb_date_time_info').remove();
					});
					
				});

				
			}); 

			// Ajax Submit .tfhb-meeting-form.ajax-submit'  
			$this.find('.tfhb-meeting-form.ajax-submit').on('submit', function (e) {
				e.preventDefault(); 
				var data  = new FormData(this); 
				// make this form data as Object
				var InformationData = {};
				data.forEach(function(value, key){
					InformationData[key] = value;
				}); 
				
				
				tfhb_from_submission($this, preloader, InformationData, calenderData);
			});
			document.addEventListener( 'wpcf7mailsent', function( event ) {
				var data = event.detail.formData; 
				if(calenderData.questions_type == 'existing' && calenderData.questions_form_type == 'wpcf7'){ 
					if(event.detail.contactFormId == calenderData.questions_form){  
						var InformationData = {};
						data.forEach(function(value, key){
							InformationData[key] = value;
						});   
						tfhb_from_submission($this, preloader, InformationData, calenderData);
					}
				}
				
			});
 
			// Forminator Form Submission
			$(document).on('forminator:form:submit:success', function(event, response ) { 
				
				var InformationData = {};
				response.forEach(function(value, key){
					InformationData[key] = value;
				}); 
				
				
				tfhb_from_submission($this, preloader, InformationData, calenderData);
			});

			// Fluent Forms Form Submission
			$(document).on('fluentform_submission_success', function(event, response) {
				var data = new FormData(response.form[0]);
				var InformationData = {};
				data.forEach(function(value, key){
					InformationData[key] = value;
				}); 
				
				
				tfhb_from_submission($this, preloader, InformationData, calenderData);
			});

 
		
		});

		function tfhb_form_validation($this) {

			// has attr required
			var error = [];
			var error_message = '';
			var validation = true;
			// Form Validation 
			$this.find('.tfhb-single-form').each(function(){
			
				var $this_form_field = $(this);
				
				 
				if($this_form_field.find('input').length > 0 && $this_form_field.find('input').attr('required') == 'required' && $this_form_field.find('input').val() == ''){
					// get the input name
					var input_name = $this_form_field.find('input').attr('name');
					error.push(true);
					error_message += '<p>'+input_name+' field is required.</p>';
					
				}
				
			});
 
			// if in array any error true then show the error
			if(error.includes(true)){ 
				$this.find('.tfhb-notice').html(error_message);
				$this.find('.tfhb-notice').show();
				validation = false;
			}

			return validation;
		}

		// render_paypal_payment
		function tfhb_render_paypal_payment($this, responseData){
			var paypal_button = $this.find('.tfhb-paypal-button-container');
			var confirmation_template = responseData.confirmation_template;
			// hide the form .tfhb-confirmation-button
			$this.find('.tfhb-confirmation-button').hide(); 
			$this.find('.wpcf7').hide(); 
			let currency = typeof tfhb_app_booking.general_settings.currency !== 'undefined' && tfhb_app_booking.general_settings.currency != '' ? tfhb_app_booking.general_settings.currency : 'USD';
		 
			// Render PayPal button into the container
			paypal.Buttons({
				// Create an order
				createOrder: function (data, actions) {  

					return actions.order.create({
						
						purchase_units: [{
							reference_id : (responseData.data && responseData.data.draft_token) ? responseData.data.draft_token : responseData.data.attendee_data.id,
							description: responseData.data.meeting.title + ' - ' + responseData.data.meeting.duration + ' Minutes | ' + responseData.data.booking.start_time + ' - ' + responseData.data.booking.end_time + ' | ' + responseData.data.booking.meeting_dates,
							custom_id: (responseData.data && responseData.data.draft_token) ? responseData.data.draft_token : responseData.data.attendee_data.id,
							amount: {
								currency_code: currency,
								value: responseData.data.meeting.meeting_price,// Set the transaction amount
							}
						}]
					});
				},
		
				// On successful payment
				onApprove: function (data, actions) {
					return actions.order.capture().then(function (details) {
  
						$.ajax({
							url: tfhb_app_booking.ajax_url, 
							type: 'POST',
							data: {
								nonce: tfhb_app_booking.nonce, 
								action: 'tfhb_meeting_paypal_payment_confirmation',
								payment_details: details,
								responseData: responseData,
							}, 
							success: function (response) {
								if(response.success){
									$this.find('.tfhb-meeting-card').html(''); 
									const tmpl = (response.data && response.data.confirmation_template) ? response.data.confirmation_template : confirmation_template;
									$this.find('.tfhb-meeting-card').append(tmpl); 
								}else{
									$this.find('.tfhb-notice').html(response.data.message);
									$this.find('.tfhb-notice').show();
								}
							},
							error: function (error) {
								console.log(error);
							}
						}); 
						 
					});
				},
		
				// If the buyer cancels the payment
				onCancel: function (data) {
					
				},
		
				// If there is an error
				onError: function (err) {
					console.error('An error occurred during the transaction', err);
					alert('Payment could not be completed due to an error');
				}
		
			}).render('.tfhb-paypal-button-container');
		}


		function tfhb_render_stripe_payment($this, responseData, stripe_public_key, meeting_title) {
			$this.find('.tfhb-confirmation-button').hide();
			let currency = typeof tfhb_app_booking.general_settings.currency !== 'undefined' && tfhb_app_booking.general_settings.currency != '' ? tfhb_app_booking.general_settings.currency : 'USD';
			if (responseData && responseData.data && responseData.data.meeting && responseData.data.meeting.payment_currency) {
				currency = responseData.data.meeting.payment_currency.toUpperCase();
			}

			// If server returned a stripe error (e.g. amount below minimum), display notice
			if (responseData && responseData.stripe_error) {
				$this.find('.tfhb-notice').html(responseData.stripe_error).show();
				$this.find('.tfhb-booking-submit').removeAttr('disabled');
				$this.find('.tfhb-booking-submit .tfhb-submit-preloader').remove();
				return;
			}

			$this.find('.wpcf7').hide(); 

			const stripeButtonContainer = $this.find('.tfhb-stripe-button-container');
			const confirmation_template = responseData.confirmation_template;
			const meetingData = (responseData.data && responseData.data.meeting) ? responseData.data.meeting : {};
			const price = meetingData.meeting_price ? meetingData.meeting_price : '0';

			// Active credentials from response or fallback
			const stripeMeta = responseData.data && responseData.data.stripe ? responseData.data.stripe : null;
			const activePublicKey = (stripeMeta && stripeMeta.publishable_key) ? stripeMeta.publishable_key : stripe_public_key;
			const isTestMode = stripeMeta ? stripeMeta.test_mode : (activePublicKey && activePublicKey.indexOf('pk_test_') === 0);

			const rawCurrency = (meetingData.payment_currency || (stripeMeta && stripeMeta.currency) || 'USD').toUpperCase();
			const currencySymbols = {
				USD: '$',
				EUR: '€',
				GBP: '£',
				CAD: 'CA$',
				AUD: 'A$',
				JPY: '¥',
				BDT: '৳',
				INR: '₹',
				CNY: '¥',
			};
			const currencySymbol = currencySymbols[rawCurrency] || (rawCurrency + ' ');
			const displayPrice = parseFloat(price).toFixed(2);

			if (!activePublicKey) {
				$this.find('.tfhb-notice').html('Stripe Publishable Key is not configured. Please contact the administrator.').show();
				return;
			}

			// Render WooCommerce-style card layout
			let cardHtml = `
				<div class="tfhb-stripe-card-box tfhb-mt-16">
					<div class="tfhb-stripe-card-header tfhb-flexbox tfhb-align-center tfhb-gap-8 tfhb-mb-16">
						<svg class="tfhb-card-header-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
							<rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
							<line x1="1" y1="10" x2="23" y2="10"></line>
						</svg>
						<span class="tfhb-stripe-header-title">Card</span>
						${isTestMode ? '<span class="tfhb-badge tfhb-badge-test" style="margin-left: auto; background: #fff3cd; color: #856404; font-size: 11px; padding: 2px 8px; border-radius: 4px; font-weight: 600;">Test Mode</span>' : ''}
					</div>

					${isTestMode ? `
						<div class="tfhb-stripe-test-helper" style="background: #fdf8e2; border: 1px dashed #e0c870; padding: 8px 12px; border-radius: 6px; font-size: 12px; color: #705814; margin-bottom: 14px;">
							<strong>Test Card:</strong> Use <code>4242 4242 4242 4242</code> with any future expiration and 3-digit CVC.
						</div>
					` : ''}

					<!-- Card Number Field -->
					<div class="tfhb-stripe-field-group" id="tfhb-field-wrap-card-number">
						<label class="tfhb-stripe-field-label" for="tfhb-stripe-card-number">Card number</label>
						<div class="tfhb-stripe-input-row tfhb-flexbox tfhb-align-center tfhb-justify-between">
							<div id="tfhb-stripe-card-number" class="tfhb-stripe-element-field"></div>
							<div class="tfhb-stripe-card-brands tfhb-flexbox tfhb-gap-4">
								<svg class="tfhb-card-brand-svg tfhb-card-brand-visa" width="34" height="22" viewBox="0 0 32 20" fill="none"><rect width="32" height="20" rx="3" fill="#0A2540"/><path d="M13.2 13.5L14.7 6.5H16.6L15.1 13.5H13.2ZM21.3 6.7C21 6.5 20.4 6.3 19.7 6.3C18 6.3 16.7 7.2 16.7 8.5C16.7 9.5 17.6 10 18.3 10.3C19 10.7 19.3 10.9 19.3 11.2C19.3 11.7 18.7 11.9 18.1 11.9C17.4 11.9 17 11.8 16.4 11.5L16.1 11.4L15.8 13C16.3 13.2 17.2 13.4 18 13.4C19.8 13.4 21.1 12.5 21.1 11.1C21.1 10.2 20.5 9.7 19.4 9.2C18.8 8.9 18.4 8.7 18.4 8.4C18.4 8 18.8 7.8 19.5 7.8C20.1 7.8 20.6 7.9 20.9 8.1L21.1 8.2L21.3 6.7ZM25.2 6.5H23.7C23.2 6.5 22.9 6.7 22.7 7.1L20 13.5H21.9L22.3 12.4H24.7L25 13.5H26.7L25.2 6.5ZM22.8 10.9L23.7 8.4L24.3 10.9H22.8ZM12.7 6.5L10.9 11.3L10.7 10.3C10.4 9.1 9.4 7.7 8.1 7.1L9.7 13.5H11.7L14.6 6.5H12.7Z" fill="white"/></svg>
								<svg class="tfhb-card-brand-svg tfhb-card-brand-mastercard" width="34" height="22" viewBox="0 0 32 20" fill="none"><rect width="32" height="20" rx="3" fill="#252525"/><circle cx="12" cy="10" r="6" fill="#EB001B"/><circle cx="20" cy="10" r="6" fill="#F79E1B" fill-opacity="0.9"/><path d="M16 5.8C14.7 7 13.8 8.4 13.8 10C13.8 11.6 14.7 13 16 14.2C17.3 13 18.2 11.6 18.2 10C18.2 8.4 17.3 7 16 5.8Z" fill="#FF5F00"/></svg>
								<svg class="tfhb-card-brand-svg tfhb-card-brand-amex" width="34" height="22" viewBox="0 0 32 20" fill="none"><rect width="32" height="20" rx="3" fill="#0070D1"/><path d="M7 6.5H9.5L11 10.5L12.5 6.5H15V13.5H13.3V8.8L11.8 12.8H10.2L8.7 8.8V13.5H7V6.5Z" fill="white"/></svg>
								<svg class="tfhb-card-brand-svg tfhb-card-brand-discover" width="34" height="22" viewBox="0 0 32 20" fill="none"><rect width="32" height="20" rx="3" fill="#FF6000"/><circle cx="16" cy="10" r="4.5" fill="#FFFFFF"/><path d="M7 7.5H10C11.5 7.5 12.5 8.5 12.5 10C12.5 11.5 11.5 12.5 10 12.5H7V7.5Z" fill="white"/></svg>
							</div>
						</div>
					</div>

					<!-- Expiration Date Field -->
					<div class="tfhb-stripe-field-group" id="tfhb-field-wrap-card-expiry">
						<label class="tfhb-stripe-field-label" for="tfhb-stripe-card-expiry">Expiration date</label>
						<div id="tfhb-stripe-card-expiry" class="tfhb-stripe-element-field"></div>
					</div>

					<!-- Security Code Field -->
					<div class="tfhb-stripe-field-group" id="tfhb-field-wrap-card-cvc">
						<label class="tfhb-stripe-field-label" for="tfhb-stripe-card-cvc">Security code</label>
						<div class="tfhb-stripe-input-row tfhb-flexbox tfhb-align-center tfhb-justify-between">
							<div id="tfhb-stripe-card-cvc" class="tfhb-stripe-element-field"></div>
							<div class="tfhb-stripe-cvc-icon">
								<svg width="26" height="18" viewBox="0 0 28 18" fill="none"><rect x="0.5" y="0.5" width="27" height="17" rx="2.5" fill="#f8fafc" stroke="#cbd5e1"/><line x1="1" y1="5" x2="27" y2="5" stroke="#94a3b8" stroke-width="2"/><rect x="3" y="9" width="12" height="5" rx="1" fill="#e2e8f0"/><text x="17" y="13" font-size="7" font-weight="700" fill="#64748b" font-family="sans-serif">123</text></svg>
							</div>
						</div>
					</div>

					<!-- Error Notice -->
					<div id="tfhb-stripe-card-errors" class="tfhb-notice tfhb-error tfhb-mt-8" style="display: none; padding: 10px 14px; font-size: 13px; color: #d93025; background: #fdf2f2; border-left: 3px solid #d93025; border-radius: 4px;" role="alert"></div>

					<!-- Action Button (Screenshot 4 fix: prominent white text on green background) -->
					<div class="tfhb-stripe-action-btn tfhb-mt-16">
						<button type="button" class="tfhb-stripe-payment-btn" id="tfhb-stripe-submit-button">
							<svg class="tfhb-btn-lock-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
								<rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
								<path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
							</svg>
							<span class="tfhb-stripe-btn-text">Pay ${currencySymbol}${displayPrice}</span>
						</button>
					</div>
				</div>
			`;

			stripeButtonContainer.html(cardHtml);
			stripeButtonContainer.show();

			// Ensure Stripe.js is loaded
			function initializeStripeElements() {
				if (typeof Stripe !== 'function') {
					console.error('Stripe.js v3 is not available.');
					return;
				}

				const stripe = Stripe(activePublicKey);
				const elements = stripe.elements();

				// Get primary theme color from CSS variables if available
				const primaryColor = getComputedStyle(document.documentElement).getPropertyValue('--tfhb-primary-color') || '#2E6B38';

				const elementStyles = {
					base: {
						color: '#1a1f36',
						fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
						fontSmoothing: 'antialiased',
						fontSize: '15px',
						lineHeight: '22px',
						'::placeholder': {
							color: '#a0aec0',
						},
					},
					invalid: {
						color: '#d93025',
						iconColor: '#d93025',
					},
				};

				const cardNumber = elements.create('cardNumber', {
					style: elementStyles,
					showIcon: false,
				});
				const cardExpiry = elements.create('cardExpiry', {
					style: elementStyles,
				});
				const cardCvc = elements.create('cardCvc', {
					style: elementStyles,
				});

				cardNumber.mount('#tfhb-stripe-card-number');
				cardExpiry.mount('#tfhb-stripe-card-expiry');
				cardCvc.mount('#tfhb-stripe-card-cvc');

				// Focus / blur handlers
				cardNumber.on('focus', function () {
					$('#tfhb-field-wrap-card-number').addClass('tfhb-stripe-focused');
				});
				cardNumber.on('blur', function () {
					$('#tfhb-field-wrap-card-number').removeClass('tfhb-stripe-focused');
				});
				cardExpiry.on('focus', function () {
					$('#tfhb-field-wrap-card-expiry').addClass('tfhb-stripe-focused');
				});
				cardExpiry.on('blur', function () {
					$('#tfhb-field-wrap-card-expiry').removeClass('tfhb-stripe-focused');
				});
				cardCvc.on('focus', function () {
					$('#tfhb-field-wrap-card-cvc').addClass('tfhb-stripe-focused');
				});
				cardCvc.on('blur', function () {
					$('#tfhb-field-wrap-card-cvc').removeClass('tfhb-stripe-focused');
				});

				// Real-time error handling & brand highlighting
				function handleFieldChange(event) {
					const displayError = $('#tfhb-stripe-card-errors');
					if (event.error) {
						displayError.text(event.error.message).show();
					} else {
						displayError.text('').hide();
					}

					if (event.elementType === 'cardNumber' && event.brand) {
						const brand = event.brand;
						$('.tfhb-card-brand-svg').removeClass('tfhb-brand-active tfhb-brand-dimmed');
						if (brand && brand !== 'unknown') {
							$('.tfhb-card-brand-svg').addClass('tfhb-brand-dimmed');
							$('.tfhb-card-brand-' + brand).removeClass('tfhb-brand-dimmed').addClass('tfhb-brand-active');
						}
					}
				}

				cardNumber.on('change', handleFieldChange);
				cardExpiry.on('change', handleFieldChange);
				cardCvc.on('change', handleFieldChange);

				// Handle payment button click
				stripeButtonContainer.off('click', '.tfhb-stripe-payment-btn').on('click', '.tfhb-stripe-payment-btn', function (e) {
					e.preventDefault();

					const $btn = $(this);
					const $errorBox = $('#tfhb-stripe-card-errors');
					$errorBox.hide().text('');

					const submitPreLoader = `
						<span class="tfhb-submit-preloader" style="margin-left: 8px;">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: inline-block; background: transparent;" width="18" height="18">
								<circle stroke-dasharray="188.49555921538757 64.83185307179586" r="40" stroke-width="6" stroke="#ffffff" fill="none" cy="50" cx="50">
									<animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="0.6s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
								</circle>
							</svg>
						</span>`;

					$btn.attr('disabled', 'disabled').addClass('disabled');
					$btn.append(submitPreLoader);

					const attendeeData = responseData.data && responseData.data.attendee_data ? responseData.data.attendee_data : {};
					const attendeeName = attendeeData.name || attendeeData.attendee_name || '';
					const attendeeEmail = attendeeData.email || attendeeData.attendee_email || '';

					function processConfirmation(clientSecret) {
						const confirmParams = {
							payment_method: {
								card: cardNumber,
								billing_details: {
									name: attendeeName,
									email: attendeeEmail,
								},
							},
						};

						function confirmOnServer(intentId) {
							jQuery.ajax({
								url: tfhb_app_booking.ajax_url,
								type: 'POST',
								data: {
									nonce: tfhb_app_booking.nonce,
									action: 'tfhb_meeting_stripe_payment_confirmation',
									payment_intent_id: intentId,
									responseData: responseData,
								},
								success: function (presponse) {
									if (presponse.success) {
										$this.find('.tfhb-meeting-card').html('');
										const tmpl = (presponse.data && presponse.data.confirmation_template) ? presponse.data.confirmation_template : confirmation_template;
										$this.find('.tfhb-meeting-card').append(tmpl);
									} else {
										const errMsg = presponse.data && presponse.data.message ? presponse.data.message : 'Payment verification failed.';
										$errorBox.text(errMsg).show();
										$btn.removeAttr('disabled').removeClass('disabled');
										$btn.find('.tfhb-submit-preloader').remove();
									}
								},
								error: function (xhr) {
									let errMsg = 'Server verification failed. Please try again or contact support.';
									if (xhr.responseJSON && xhr.responseJSON.data && xhr.responseJSON.data.message) {
										errMsg = xhr.responseJSON.data.message;
									}
									$errorBox.text(errMsg).show();
									$btn.removeAttr('disabled').removeClass('disabled');
									$btn.find('.tfhb-submit-preloader').remove();
								},
							});
						}

						stripe.confirmCardPayment(clientSecret, confirmParams).then(function (result) {
							if (result.error) {
								// If an error is returned (e.g. payment already succeeded and card was re-submitted), check intent status
								stripe.retrievePaymentIntent(clientSecret).then(function (retrieved) {
									if (retrieved.paymentIntent && (retrieved.paymentIntent.status === 'succeeded' || retrieved.paymentIntent.status === 'processing')) {
										confirmOnServer(retrieved.paymentIntent.id);
									} else {
										$errorBox.text(result.error.message).show();
										$btn.removeAttr('disabled').removeClass('disabled');
										$btn.find('.tfhb-submit-preloader').remove();
									}
								}).catch(function () {
									$errorBox.text(result.error.message).show();
									$btn.removeAttr('disabled').removeClass('disabled');
									$btn.find('.tfhb-submit-preloader').remove();
								});
							} else if (result.paymentIntent && (result.paymentIntent.status === 'succeeded' || result.paymentIntent.status === 'processing')) {
								confirmOnServer(result.paymentIntent.id);
							}
						}).catch(function (err) {
							stripe.retrievePaymentIntent(clientSecret).then(function (retrieved) {
								if (retrieved.paymentIntent && (retrieved.paymentIntent.status === 'succeeded' || retrieved.paymentIntent.status === 'processing')) {
									confirmOnServer(retrieved.paymentIntent.id);
								} else {
									$errorBox.text(err.message || 'Payment processing error.').show();
									$btn.removeAttr('disabled').removeClass('disabled');
									$btn.find('.tfhb-submit-preloader').remove();
								}
							}).catch(function () {
								$errorBox.text(err.message || 'Payment processing error.').show();
								$btn.removeAttr('disabled').removeClass('disabled');
								$btn.find('.tfhb-submit-preloader').remove();
							});
						});
					}

					// Use pre-generated client_secret if available, or create dynamically
					if (stripeMeta && stripeMeta.client_secret) {
						processConfirmation(stripeMeta.client_secret);
					} else {
						jQuery.ajax({
							url: tfhb_app_booking.ajax_url,
							type: 'POST',
							data: {
								nonce: tfhb_app_booking.nonce,
								action: 'tfhb_stripe_create_payment_intent',
								amount: price,
								currency: rawCurrency.toLowerCase(),
								booking_id: responseData.data.booking_id,
								attendee_id: responseData.data.attendee_id,
								draft_token: (responseData.data && responseData.data.draft_token) ? responseData.data.draft_token : '',
								description: meeting_title,
							},
							success: function (intentRes) {
								if (intentRes.success && intentRes.data.client_secret) {
									processConfirmation(intentRes.data.client_secret);
								} else {
									const errMsg = intentRes.data && intentRes.data.message ? intentRes.data.message : 'Could not initialize payment session.';
									$errorBox.text(errMsg).show();
									$btn.removeAttr('disabled').removeClass('disabled');
									$btn.find('.tfhb-submit-preloader').remove();
								}
							},
							error: function () {
								$errorBox.text('Could not initialize payment intent.').show();
								$btn.removeAttr('disabled').removeClass('disabled');
								$btn.find('.tfhb-submit-preloader').remove();
							},
						});
					}
				});
			}

			// If Stripe.js is not loaded yet, load it dynamically
			if (typeof Stripe !== 'function') {
				$.getScript('https://js.stripe.com/v3/', function () {
					initializeStripeElements();
				});
			} else {
				initializeStripeElements();
			}
		}

		function tfhb_from_submission($this, preloader, InformationData, calenderData){ 
			let submitPreLoader = `<span class="tfhb-submit-preloader"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: block; background: transparent;" width="200" height="200" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-dasharray="188.49555921538757 64.83185307179586" r="40" stroke-width="4" stroke="#ffffff" fill="none" cy="50" cx="50">
			<animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="0.49751243781094534s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
		  </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg><span>`;

			$this.find('.tfhb-booking-submit').append(submitPreLoader); 
			$this.find('.tfhb-booking-submit').attr('disabled', 'disabled');
			
 
			// Interval to show the preloader
			$this.find('.tfhb-notice').hide();
			$this.find('.tfhb-notice').html(''); 

		   var meeting_title = $this.find(".tfhb-meeting-details h2").text();
		   var meeting_id = $this.find("#meeting_id").val();
		   var host_id = $this.find("#host_id").val();
		   var meeting_duration = $this.find("#meeting_duration").val();
		   var meeting_dates = $this.find("#meeting_dates").val();
		   var meeting_time_start = $this.find("#meeting_time_start").val();
		   var meeting_time_end = $this.find("#meeting_time_end").val(); 
		   var booking_hash = $this.find("#booking_hash").val(); 
		   var action_type = $this.find("#action_type").val(); 
		   var reschedule_nonce = $this.find("#reschedule_nonce").val();
		   var meeting_price = $this.find("#meeting_price").val(); 
		   var recurring_maximum = $this.find("#recurring_maximum").val(); 
		   var attendee_time_zone = $this.find("#attendee_time_zone_"+calenderData.meeting_id).val(); 
		   var tfhb_time_format = $this.find("#tfhb_time_format").val(); 
		   var name = $this.find("#name").val(); 
		   var email = $this.find("#email").val(); 
		   var address = $this.find("#address").val(); 

		   var payment_type = $this.find("#payment_method").val();
		   var meeting_price = $this.find("#meeting_price").val();
		   var payment_amount = $this.find("#payment_amount").val();
		   var stripe_public_key = $this.find("#stpublic_key").val();
		   var paypal_public_key = $this.find("#paypal_public_key").val();
		   var payment_currency = $this.find("#payment_currency").val(); 

			//    Payment Status
		   	var payment_status = calenderData.payment_status;
		

		   var data  = {
			action: 'tfhb_meeting_form_submit',
			nonce: tfhb_app_booking.nonce,
			meeting_id: meeting_id,
			host_id: host_id,
			meeting_dates: meeting_dates,
			meeting_duration: meeting_duration,
			meeting_time_start: meeting_time_start,
			meeting_time_end: meeting_time_end,
			booking_hash: booking_hash,
			action_type: action_type,
			reschedule_nonce: reschedule_nonce,
			recurring_maximum: recurring_maximum,
			attendee_time_zone: attendee_time_zone,
			tfhb_time_format: tfhb_time_format,
			payment_type: payment_type,
			meeting_price: meeting_price,
			payment_amount: payment_amount,
			stripe_public_key: stripe_public_key,
			payment_currency: payment_currency,
		}; 
		
		// Push object information data to data
		data = Object.assign(InformationData, data); 
			if(payment_status == 1 && "" == payment_type){ 
				//   5 seconds
				setTimeout(function(){ 
					$this.find('.tfhb-notice').append( tfhbTranslate('Payment Method Required.' ));
					$this.find('.tfhb-notice').show();
					$this.find('.tfhb-booking-submit .tfhb-submit-preloader').remove();
					$this.find('.tfhb-booking-submit').remove('.tfhb-submit-preloader'); 
					//    Remove Disabled
					$this.find('.tfhb-booking-submit').removeAttr('disabled');  
				},  1000); // 2000 milliseconds = 2 seconds
			
				
			}

		   if(payment_status != 1 || ( payment_status == 1 && "woo_payment"==payment_type ) || ( payment_status == 1 && "paypal_payment"==payment_type ) || ( payment_status == 1 && "stripe_payment"==payment_type ) ){
			  
			 
			   $.ajax({
				   url: tfhb_app_booking.ajax_url, 
				   type: 'POST',
				   action: 'tfhb_meeting_form_submit',
				   data: data, 
				   success: function (response) {
					
					$this.find('.tfhb-booking-submit .tfhb-submit-preloader').remove();  
					//   Remove Disabled
					$this.find('.tfhb-booking-submit').removeAttr('disabled');
					   if(response.success){
								
							$this.find('.tfhb-booking-submit').remove('.tfhb-submit-preloader'); 
							//    Remove Disabled
						   $this.find('.tfhb-booking-submit').removeAttr('disabled');
						   
						   // Render Paypal Payment System
						   if(payment_status == 1 && "paypal_payment" == payment_type && response.data.data){ 
								tfhb_render_paypal_payment($this, response.data);
								return
							}
							if(payment_status == 1 && "stripe_payment" == payment_type && response.data.data){
								tfhb_render_stripe_payment($this, response.data, stripe_public_key, meeting_title);
								return
							}
						   if(response.data.redirect){
							   window.location.href = response.data.redirect;
							   return;

						   }else{ 
							   $this.find('.tfhb-meeting-card').html(''); 
							   $this.find('.tfhb-meeting-card').append(response.data.confirmation_template); 
							   if(response.data.action == 'rescheduled'){
								   $this.find('.tfhb-meeting-hostinfo').append(`
										   <div class="tfhb-notice " > 
										   <span>`+response.data.message+` </span>
									   </div>`
								   )
							   }

						   } 

					   }else{ 
						   $this.find('.tfhb-notice').append(response.data.message);
						   $this.find('.tfhb-notice').show();
						   return false;
					   }
				   },
				   error: function (error) {
					   console.log(error);
				   }
			   });
		   }

		}

		
		function tfhb_date_manipulate($this, calenderData, year, month, date, months) {
			const day = $this.find(".tfhb-calendar-dates");
			const weekdays = $this.find(".tfhb-calendar-weekdays");
			const currdate = $this.find(".tfhb-calendar-current-date");
		
			let calender_data = calenderData;
			let availability = calender_data.availability;
			let date_slots = availability.date_slots;  
			
			let time_slots = availability.time_slots;   
			let availability_range = calender_data.availability_range;   
			let availability_range_type = calender_data.availability_range_type;   
			let availabilitys_range_start = calender_data.availability_range.start;   
			let availabilitys_range_end = calender_data.availability_range.end;   
			let availabilityRangeStartDate = null;
			let availabilityRangeEndDate = null;
			if (availabilitys_range_start) {
				availabilityRangeStartDate = (availabilitys_range_start.includes('T') || availabilitys_range_start.includes(' '))
					? new Date(availabilitys_range_start)
					: new Date(availabilitys_range_start + 'T00:00:00');
			}
			if (availabilitys_range_end) {
				availabilityRangeEndDate = (availabilitys_range_end.includes('T') || availabilitys_range_end.includes(' '))
					? new Date(availabilitys_range_end)
					: new Date(availabilitys_range_end + 'T23:59:59.999');
			}
		
			let dayNameText = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
			let dayShortText = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
			let DisableDays = [];
		
			// Use dynamic start day if available 
			let week_start_from = tfhb_app_booking.general_settings.week_start_from || 'Sunday';
			let weekStartIndex = dayNameText.indexOf(week_start_from);
			if (weekStartIndex === -1) weekStartIndex = 0;
		
			//  Update Weekday DOM Based on week_start_from
			let adjustedWeekdays = [];
			for (let i = 0; i < 7; i++) {
				let index = (weekStartIndex + i) % 7;
				adjustedWeekdays.push(`<li>${tfhbTranslate(dayShortText[index])}</li>`);
			}
			weekdays.html(adjustedWeekdays.join(""));
		
			//  Disable Days
			for (let i = 0; i < time_slots.length; i++) { 
				if (time_slots[i].status === false || time_slots[i].status == false) {
					DisableDays.push(time_slots[i].day);
				}
			}
		
			//  Day logic based on week start
			let actualDayOne = new Date(year, month, 1).getDay();
			let dayone = (actualDayOne - weekStartIndex + 7) % 7;
			let lastdate = new Date(year, month + 1, 0).getDate();
			let actualDayEnd = new Date(year, month, lastdate).getDay();
			let dayend = (actualDayEnd - weekStartIndex + 7) % 7;
			let monthlastdate = new Date(year, month, 0).getDate();
		
			let lit = "";
		
			//  Previous month's trailing days
			for (let i = dayone; i > 0; i--) {
				lit += `<li class="inactive">${tfhbTranslateNumber(monthlastdate - i + 1)}</li>`;
			}
		
	
			//  Current month dates
			for (let i = 1; i <= lastdate; i++) { 
				let isToday = i === date.getDate() && month === new Date().getMonth() && year === new Date().getFullYear() ? "active" : "";
				let dateKey = `${year}-${(month + 1).toString().padStart(2, '0')}-${i.toString().padStart(2, '0')}`;
				let dateSlot = typeof date_slots !== 'undefined' ? date_slots.find(slot => slot.date.match(dateKey)) : ""; 
				let availabilityClass = (typeof dateSlot !== 'undefined' && dateSlot !== '' && dateSlot.available == true) ? "inactive " : " ";
				let dataAvailable = "available";
		
				if (new Date() > new Date(year, month, i) && i !== date.getDate()) {
					availabilityClass = "inactive ";
					dataAvailable = "unavailable";
				}
		
				let currentDayName = dayNameText[new Date(year, month, i).getDay()]; 
				 
			 
				if (DisableDays.includes(currentDayName)) {
					availabilityClass = "inactive ";
					dataAvailable = "unavailable";
					isToday = '';
				}
		
				if (availability_range_type !== 'indefinitely' && availabilityRangeStartDate && availabilityRangeEndDate) {
					let currDate = new Date(year, month, i);
					if (currDate < availabilityRangeStartDate || currDate > availabilityRangeEndDate) {
						availabilityClass = "inactive ";
						dataAvailable = "unavailable";
						isToday = "";
					}
				} 

				if(typeof dateSlot !== 'undefined' && dateSlot !== '' && dateSlot.available == '') {
					availabilityClass = " ";
					dataAvailable = "available";
				}
		
				if ('active' === isToday) {
					availabilityClass = " ";
				}
		
				lit += `<li data-date="${dateKey}" data-available="${dataAvailable}" class="${isToday} current ${availabilityClass}">${tfhbTranslateNumber(i)}</li>`;
			}
		
			// ➕ Next month's leading days
			for (let i = dayend; i < 6; i++) {
				lit += `<li class="inactive">${tfhbTranslateNumber(i - dayend + 1)}</li>`;
			}
		
			currdate.text(`${tfhbTranslate(months[month])} ${tfhbTranslateNumber(year)}`);
			day.html(lit);
		}
		// Function to generate the tfhb-calendar
		function tfhb_times_manipulate($this, current_date, calenderData, callback = null) {
			  

			var $this_li = $this.find('.tfhb-calendar-dates li.active');   
			// $this.find('.tfhb-meeting-times').css("display", "block").animate({left: "0", opacity: 1, width: 224}, 400 );
			$this.find('.tfhb-available-times').addClass('inactive');
			$this.find('.tfhb-calendar-body').addClass('inactive');
			// Get the first day of the month 
			var meeting_id = $this.find("input[name='meeting_id']").val();
			var selected_date = current_date; 
			// Selectedate date format Saturday, 11 April 
			
			var data_available = $this_li.attr('data-available'); 
			//  input radio data name tfhb_time_format
			var time_format = $this.find('input[name="tfhb_time_format"]:checked').val();  
			var time_zone = $this.find('.tfhb-time-zone-select').val();
			 
			$.ajax({
				url: tfhb_app_booking.ajax_url, 
				type: 'POST',
				data: {
					action: 'tfhb_already_booked_times',
					nonce: tfhb_app_booking.nonce,
					selected_date: selected_date,
					meeting_id: meeting_id,
					time_format: time_format,
					time_zone: time_zone,
				}, 
				success: function (response) {  
					if(response.success == true){  
 
						$this.find('.tfhb-calendar-body').removeClass('inactive');  
						let data = response.data; 
						calenderData.calander_available_time_slot = response.data;
						 
						if (typeof callback === "function") {
							callback(); // Execute the callback function
						}
					}
					if(response.success == false){ 
						$this.find('.tfhb-available-times').removeClass('inactive');
						$this.find('.tfhb-calendar-body').removeClass('inactive');
						$this.find('.tfhb-available-times').html('');
						$this.find('.tfhb-available-times').append('<ul></ul>');
						$this.find('.tfhb-available-times ul').append('<li > <p>'+response.data.message+'</p></li>');
						$this.find('.tfhb-meeting-times').css("display", "block").animate({left: "0", opacity: 1, width: 224}, 400 );
						
					}
				},
				error: function (error) {
					console.log(error);
				}
			});
		 
			

			 

		}

		// Generate Time Slots
		function generateTimeSlots(startTime, endTime, duration, meeting_interval, buffer_time_before, buffer_time_after, selected_date, time_format, time_zone) {
			var timeSlots = [];

			var skip_before_meeting_start = tfhb_app_booking.general_settings.allowed_reschedule_before_meeting_start; // exp 100 minutes
			// start date data format =   2024-05-04 
			var start = new Date(selected_date + " " + startTime);
			var end = new Date(selected_date + " " + endTime);
			var current = new Date(start);
			var before = new Date(start);
			var after = new Date(start);
			var diff = duration * 60000;
			var before_diff = buffer_time_before * 60000;
			var after_diff = buffer_time_after * 60000;
			var meeting_interval = meeting_interval * 60000;
			var total_diff = diff +before_diff + after_diff;
			while (current < end) {
				
				
				// new Date(current.getTime() + total_diff).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
				var start_time = formatTime(current, time_format, time_zone);
				var end_time = formatTime(new Date(current.getTime() + total_diff), time_format, time_zone);

			   // if current time is passed then skip skip_before_meeting_start
			  
			   if(new Date() > new Date(current.getTime() - skip_before_meeting_start * 60000)){
					current = new Date(current.getTime() + total_diff + meeting_interval);
					continue;
				}
				timeSlots.push({

					start: start_time, 
					// before_diff and after_diff need to use 
					end: end_time,

				});
				current = new Date(current.getTime() + total_diff + meeting_interval);
			} 
			return timeSlots;
		}

		function formatTime(date, timeFormat, timeZone) {
			var options = {
				hour: '2-digit',
				minute: '2-digit',
				hour12: timeFormat === '12',
				timeZone: timeZone
			};
			return date.toLocaleTimeString([], options);
		} 

    });

})(jQuery);

 
