(function ($) {
    let submitPreLoader = `<span class="tfhb-submit-preloader"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: block; background: transparent;" width="200" height="200" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle stroke-dasharray="188.49555921538757 64.83185307179586" r="40" stroke-width="4" stroke="#ffffff" fill="none" cy="50" cx="50">
    <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="0.49751243781094534s" repeatCount="indefinite" type="rotate" attributeName="transform"></animateTransform>
  </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg><span>`;
    $(document).ready(function () { 
        // Cencel Booking If .tfhb-meeting-cencel-form form submit using ajax
		
        $(document).on('submit', '.tfhb-meeting-cencel-form', function (e) {  
            e.preventDefault();  
            $this = $(this);
            var data  = new FormData(this); 
            $this.find('.tfhb-booking-submit').append(submitPreLoader); 
			$this.find('.tfhb-booking-submit').attr('disabled', 'disabled');
            data.append('action', 'tfhb_meeting_form_cencel'); 
            $this.find('.tfhb-notice').remove(); 
            $.ajax({
                url: tfhb_app_booking.ajax_url, 
                type: 'POST',
                data: data, 
                processData: false,
                contentType: false,
                success: function (response) {
                    $this.find('.tfhb-booking-submit').remove('.tfhb-submit-preloader'); 
                    if(response.success){
                    
                        $this.find('.tfhb-meeting-confirmation .tfhb-forms').html('');
                        $this.find('.tfhb-meeting-confirmation').append(`<div class="tfhb-notice tfhb-success">${response.data.message}</div>`);

                    }else{ 
                        $this.find('.tfhb-meeting-confirmation').append(`<div class="tfhb-notice tfhb-error">${response.data.message}</div>`);
                        
                    }
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });
	}) 

})(jQuery);

 